### ISSUE TITLE
Error with input_dt

### ISSUE THREAD

**Issue by johnnybonney** [setzler/eventStudy#1]
Toshi brought this to my attention. Running the following throws an error:

```
test_dt <- ES_simulate_data()
ES(test_dt$observed, outcomevar = "outcome", unit_var = "individual",
   cal_time_var = "year", onset_time_var = "treatment_year",
   cluster_vars = "individual")
```
The error raised is `Error in withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) : object 'input_dt' not found`

It stems from line 73 in `combined.R`, when `input_dt` is referenced. This is the only reference to `input_data` in the file (`input_data` is widely used in `clean_data.R`). Perhaps `long_data` is what was meant to be referenced? I would be happy to fix this if someone gave me push access to the repository.

**Comment by davidnov** [comment]
Yep, that should be `long_data` instead of `input_dt--` thanks for pointing this out. I have corrected this and pushed it to the repository.
