### ISSUE TITLE
Copying data.table significantly increases estimation time

### ISSUE THREAD

**Issue by johnnybonney** [setzler/eventStudy#10]
The copy here and in `estimate_ATT.R` greatly increases the estimation time. For smaller datasets, this difference is trivial, but in larger datasets, it becomes a real impediment.

https://github.com/setzler/eventStudy/blob/d424f7a3ff10d09d5894f6dc104366917a31cefd/eventStudy/R/clean_data.R#L23

**Comment by davidnov** [comment]
I have removed the `copy()` statements throughout -- we included these as sometimes it can be difficult to predict whether the underlying data set is changed during the function.

If you wouldn't mind running the case that was giving you trouble before, I'd be interested just how much this frees up memory and speeds up your estimation. Then feel free to close.

**Comment by davidnov** [comment]
@johnnybonney Did you have a chance to see what the speed / memory improvement looks like in your case (if any)?

**Comment by johnnybonney** [comment]
@davidnov We don't have access to the original data until Toshi is back in Belgium. However, I have simulated a large representative dataset and just started running a benchmark with a few replications to get a good estimate of the change in speed and memory. I will post results on here once everything is done running.

**Comment by johnnybonney** [comment]
It seems like the new code only increases estimation speed by about 1/11 and decreases memory usage by only about 4% (however, in cases where the original `data.table` has many other columns, this change may be more drastic). So, these results don't match up with my priors... But I appreciate your work.

```
# Simulate -------------------------------------------
my_dt <- ES_simulate_data(units = 1e5,
                          min_cal_time = 2002,
                          max_cal_time = 2014,
                          min_onset_time = 2003,
                          max_onset_time = 2013)$observed

# Test speed ------------------------------------------
library(rbenchmark)
benchmark("old" = {
  res <- ES_old(my_dt, outcomevar = "outcome", unit_var = "individual",
                cal_time_var = "year", onset_time_var = "treatment_year",
                residualize_covariates = F, cluster_vars = "individual")
          },
          "new" = {
  res <- ES(my_dt, outcomevar = "outcome", unit_var = "individual",
            cal_time_var = "year", onset_time_var = "treatment_year",
            residualize_covariates = F, cluster_vars = "individual")
           },
replications = 10,
columns = c("test", "replications", "elapsed",
            "relative", "user.self", "sys.self"))

# Test memory ---------------------------------------
library(profmem)
options(profmem.threshold = 2000)  # only capture memory allocations > 2 kb

p.old <- profmem({
  ES_old(my_dt, outcomevar = "outcome", unit_var = "individual",
              cal_time_var = "year", onset_time_var = "treatment_year",
              residualize_covariates = F, cluster_vars = "individual")
  })
p.new <- profmem({
  ES(my_dt, outcomevar = "outcome", unit_var = "individual",
     cal_time_var = "year", onset_time_var = "treatment_year",
     residualize_covariates = F, cluster_vars = "individual")
})
``` 

**Speed results:**
```
  test replications elapsed relative user.self sys.self
2  new           10 1768.86    1.000   1877.61   204.50
1  old           10 1953.06    1.104   1986.82   233.21
```
**Memory results:**
```
> total(p.new) / total(p.old)
[1] 0.9602918
```
