### ISSUE TITLE
Error when using weights (due to updated weighted means)

### ISSUE THREAD

**Issue by johnnybonney** [setzler/eventStudy#14]
This line leads to an issue when using estimation weights, since `ES_treat_count_V1` is referenced just five lines later (and also further onward): `object 'ES_treat_count_V1' not found`

https://github.com/setzler/eventStudy/blob/d63468bf454d93e12fedd84cb15200621859eb9f/eventStudy/R/combined.R#L192

The same issue will arise with `ES_treat_count_V2`:

https://github.com/setzler/eventStudy/blob/d63468bf454d93e12fedd84cb15200621859eb9f/eventStudy/R/combined.R#L201

Either the version with estimation weights needs to be added, or there should be some temporary hard-coded workaround. Shouldn't it be reasonable to sum the weights [`list(treat_count_V1 = sum(get(reg_weights)))` instead of `list(treat_count_V1 = .N)`] for the version with estimation weights?

**Comment by davidnov** [comment]
@johnnybonney I agree with your suggestion, and just implemented it.
