### ISSUE TITLE
Inputs as characters directions a bit misleading

### ISSUE THREAD

**Issue by maarit-olkkola** [setzler/eventStudy#19]
Hi,

This package is great! Just for a R novice the directions that the inputs should be characters was a bit misleading, since I first interpreted it to mean that the variables should be class character and nothing obviously worked. Would be helpful to clarify this in the directions. Thanks! :)

**Comment by davidnov** [comment]
Hi @MaaritOlkkola, thank you for submitting this. I just pushed a new input check in the package that hopefully makes this issue clear with the error that is thrown. When you have a moment, please reinstall the package.

**Comment by davidnov** [comment]
I'm going to close this issue, but please follow up if there are continuing related issues.
