### ISSUE TITLE
Are there unit-fixed effects or not? The role of covariates

### ISSUE THREAD

**Issue by Halvard123** [setzler/eventStudy#20]
Hello,

Thank you for the help last time around. Since then, I have doing a few analyses with the R-package and it generally works beautifully. However, I do sit with a few questions regarding the role of covariates in the estimation methods of the event study package.

First of all, I have become slightly unsure whether there are unit-fixed effects included or not in the estimation model. For sure there must be some version of cohort-fixed effects and time or relative-time-fixed effects with interaction for the treatment effects to be estimated, but it's not clear to me whether there only are cohort-fixed effects or if there are fixed effects on the unit level like Abraham and Sun specifies for the linear two-way fixed effects models for event studies and for the standard interaction-weighted model that they advocate. This of course matters quite a lot for the inclusion of covariates, and the role of the covariates in the package is therefore my primary concern. In other words, is there only room for covariates with variation over time?

Additionally, the IPW (inverse probability weighting) option seems to change the role of the covariates somewhat,  as there seems to be matching / potential exclusion of observations based on covariates if i follow appendix C of Abraham and Sun correctly. Does the model still use unit/cohort-fixed effects when this option is included or does the actual estimation method also change somewhat? If so, what are the restrictions on covariates that can be included?

I am also a bit uncertain as to the effect of the necessarily unbalanced panels that arise due to the absorbing state of the treatment making the composition of the control group change within each cohort-effect estimation. Surely, this has the potential to cause selection in the extreme ends of the dynamic treatment estimation, and could be a point of criticism for the model when compared to a normal diff-in-diff. I understand that it is used in order to get the additional data from future treated units that have not yet been treated, but changing the composition in the control group between different periods must have some implications for the cohort-fixed effects and could easily be a point of criticism for the methodology. I guess I am wondering whether there is any literature on this issue of changes in composition of the control group and its effects or the assumptions under which it has a major or negligible influence.

Hope I am making sense here and sorry for the confusion and potentially difficult questions. If you would prefer and have the time, I would be happy to correspond through mail as well, but I am sure I will not be the last person to have these sorts of questions about the model specifics.

Best,
Halvard

**Comment by davidnov** [comment]
@Halvard123 Thanks for submitting this. I agree that others may have similar questions. Can you do a favor and split your set of questions into very concise distinct constituent parts and submit them as separate issues? That will make responses more focused, and make the resulting set of issue responses more useful to future users.

I'll close this issue meanwhile
