### ISSUE TITLE
In what ways does the IPW option change the role of covariates?

### ISSUE THREAD

**Issue by Halvard123** [setzler/eventStudy#22]
Hello,

The option IPW or inverse probability weighting causes the model to potentially exclude observations based on covariates. My interpretation is that there is some propensity score matching being done with these covariates, and that it is similar to the inverse propensity score reweighting being described by Abraham and Sun (2018) in their appendix C. Is this correct, or is this only a reweighting of cohorts based on cohort size like many other weighting methods? 

Also: does this mean that the role of covariates (when the IPW option is specified) is solely a means of matching treated individuals to matched untreated individuals or comparing a weighted average of treated individuals to a weighted average of untreated individuals with similar enough propensity scores?

Best,
Halvard

**Comment by davidnov** [comment]
Hi @Halvard123,

The `ipw=TRUE` set of options implement a reweighting of control units based on the propensity score modeled using supplied covariates, and using these propensity scores as weights in the final event study regression. You are correct that when `ipw=TRUE`, covariates are only used in estimating the propensity score, but do not enter the final event study regression directly.

**Comment by davidnov** [comment]
I'm closing this issue for now as it seems the question was answered, but feel free to re-open if not.
