### ISSUE TITLE
Underidentification with unit FE

### ISSUE THREAD

**Issue by juliaschmieder** [setzler/eventStudy#24]
Dear David, dear Bradley,
I would like to estimate the model including unit fixed effects instead of cohort fixed effects (i.e. add_units_fes = TRUE). I am aware that the identification of dynamic effects becomes more difficult in that case. I would like to follow Borusyak & Jaravel (2017), Abraham & Sun (2019), and Schmidheiny & Siegloch (2019) and impose more restrictions in the fully dynamic specification to address underidentification by choosing at least two omitted event time periods.

In my case, I have a panel with individuals observed from up to 24 time periods before to up to 12 time periods after the event (lags=t-E ranges from from -24 to 12). All individuals are treated at some point. I am interested in estimating the dynamic effects for the lags -12 to 12. I would like to normalize relative to lag -4 and additionally exclude indicators for periods more than 12 periods before the event.  

I tried to omit more than one event time categories using your command but it was not possible. Is there a way to exclude more than one time period category? Or another way to use your command to implement the described specification?

Thanks in advance
Julia

**Comment by davidnov** [comment]
Hi @juliaschmieder, the issue you describe of underidentification does not arise in the package under the identifying assumptions of parallel trends and no anticipation. Given the structure (it stacks every possible cohort-specific DiD sample), setting `add_unit_fes = TRUE` amounts to requiring that each cohort-specific DiD sample is fully balanced on the unit FE. Relatedly, there is no need to omit more than your preferred normalization year (-4).

Setting the normalization period to -4 can be done with `omitted_event_time = -4`.

**Comment by davidnov** [comment]
Hi @juliaschmieder, I am closing this for now, but if my prior response did not address your question completely, please feel free to reopen this issue.
