### ISSUE TITLE
omitted label does not adjust to command 'omitted_event_time'

### ISSUE THREAD

**Issue by Asquidy** [setzler/eventStudy#25]
in the function, ES_plot_ATTs there is an option 'omitted_event_time'. When this is changed away from the default, the text label '(Omitted)' still floats above the default.

**Comment by davidnov** [comment]
Hi @Asquidy, can you post a reproducible example here as well?

**Comment by Asquidy** [comment]
library(data.table)
library(ggplot2)
library(eventStudy)
num_periods <- 10
treatment_time <- 5

sim_data <- ES_simulate_data(units = 1000, min_cal_time = 1, max_cal_time = num_periods)[["observed"]]
sim_data[individual %% 2 == 0, treatment_year := treatment_time]
sim_data[individual %% 2 == 1, treatment_year := NA]
sim_data[, ever_treated := as.numeric(treatment_year == 5 & !is.na(treatment_year))]
sim_data[, is_treated := ifelse(!is.na(treatment_year), as.numeric(year >= treatment_year), 0)]
mean_outcome <-  mean(sim_data$outcome)

unit_trend_avg <- -.1*mean_outcome
error_sd_trend <- .5

sim_data[, unit_trend := unit_trend_avg +  rnorm(mean = 0, sd = abs(error_sd_trend*unit_trend_avg), n = .N)]

sim_data[, outcome_plus_trend := unit_trend * year * ever_treated + outcome]

sim_data2 <- copy(sim_data)
results <- ES(long_data=sim_data2, outcomevar="outcome_plus_trend", 
              unit_var="individual", cal_time_var="year", 
              onset_time_var="treatment_year", cluster_vars="individual", never_treat_action="only", linearize_pretrends = TRUE, homogeneous_ATT = TRUE, omitted_event_time = -1)

ES_plot_ATTs(results, lower_event = -3, upper_event = 5) +   ylab("ATT Estimate (95% CI)")

**Comment by davidnov** [comment]
Thank you, this helps identify the problem. `ES_plot_ATTs` is stand-alone, so it too has as `omitted_event_time` option. This should solve issue in your example:

`ES_plot_ATTs(results, lower_event = -3, upper_event = 5, omitted_event_time = -1) + ylab("ATT Estimate (95% CI)")`

**Comment by davidnov** [comment]
I'll close this for now, but if something related arises, please feel free to reopen.
