### ISSUE TITLE
Error when cluster_vars not equal to unit_var

### ISSUE THREAD

**Issue by johnnybonney** [setzler/eventStudy#3]
When the `cluster_vars` argument is not equal to the `unit_var` argument, an error is raised. Here is an example illustrating the issue:

```
test_dt <- ES_simulate_data()
my_dt <- test_dt$observed
my_dt[, group := ceiling(individual / 10)]  # variable on which to cluster

res <- ES(my_dt, outcomevar = "outcome", unit_var = "individual",
          cal_time_var = "year", onset_time_var = "treatment_year",
          cluster_vars = "group")
```

The error is `Error in eval(bysub, x, parent.frame()) : object 'group' not found`. This error occurs because `ES_clean_data()` (called in line 91) does not take `cluster_vars` as an argument and ends up dropping the `cluster_vars`. Subsequently, in line 97, `cluster_vars` will only exist if it was the same as `unit_var`. In the above example, it does not exist, causing the error.

**Comment by davidnov** [comment]
I see. Yep, you are right -- `ES_clean_data()` will trim away `group`. But it shouldn't be the case that `cluster_vars` must equal `unit_var`. For example, `cluster_vars = c("individual", "year")` should work just fine as well (I checked this on my end, but would be good if you could as well). 

So just a question of how often we expect `cluster_vars` to not be among the design variables (e.g., `unit_var`, `cal_time_var`, and `onset_time_var`). Do you have an example in mind?

**Comment by johnnybonney** [comment]
You're right. And of course, it will depend on the situation. Correct me if I am wrong here - I can imagine a case in which you are looking at treatment events that occur at a higher level than the individual (e.g., geographic or industry-level shocks), in which case you may think the error terms are correlated at that higher level (which is not a design variable).

When Toshi found this error, he was trying to deal with the multiple treatments over time issue. He is duplicating firms with multiple events [causal inference issues aside] and treats them as separate firms for estimation but wants to cluster on the actual firm ID.

If you decide not to allow clustering besides on the design variables, though, I would still recommend adding a check earlier on (with a more informative error message).

**Comment by davidnov** [comment]
Understood. I'll think about a way to just pass `cluster_vars` all the way through so that they are available for estimation.

**Comment by davidnov** [comment]
Passed `cluster_vars` through to `ES_clean_data()`. Now the user can supply any discrete variable(s) defining the clusters.
