### ISSUE TITLE
Specifying weights for estimation

### ISSUE THREAD

**Issue by johnnybonney** [setzler/eventStudy#9]
It would be very useful to be able to specify our own weights for estimation when using the ES package. The example we have in mind is when firms are treated multiple times and we want to include each event separately, but we only want each firm to be weighted once in the regression. (E.g., by using the inverse of number of events for each firm as the weight for each of that firm's events.)

**Comment by davidnov** [comment]
@johnnybonney dId you have in mind a case where `long_data` already has a variable labeled `weights` or something similar (generated and supplied by the user) that should be passed along until the final regression?

**Comment by johnnybonney** [comment]
Yes, that is exactly what we have in mind.

**Comment by davidnov** [comment]
This is now implemented as the `reg_weights` option in `ES()`. 

`reg_weights` should be set equal to the value of the weight variable supplied by the user in `long_data`

**Comment by johnnybonney** [comment]
Great, thanks for implementing this!
